cdklabs/cdk-monitoring-constructs

.projenrc.js, API.md, lib/index.ts, test/hello.test.ts
And also clean up `.projenrc.js` a bit.
=> chore: fix project build

.eslintrc.json, .projenrc.js
chore: fix eslint configuration
=> chore: fix eslint configuration

.github/workflows/build.yml, .github/workflows/release.yml, .mergify.yml, .projen/tasks.json, .projenrc.js, package.json
Adds C#, Java and Go publishers.
=> chore: add publishers for additional languages

README.md
=> chore: cleanup README contents

API.md, lib/common/metric/MetricStatistic.ts, lib/common/monitoring/alarms/LatencyAlarmFactory.ts
Adding support for 95th percentile and similar. Low level support only.
=> feat: add 95th percentile core support

.github/pull_request_template.md, .projenrc.js, CONTRIBUTING.md
Similar to the main aws-cdk project.
=> chore: add license terms in PR template [skip ci]

API.md, README.md, lib/monitoring/aws-cloudfront/CloudFrontDistributionMonitoring.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-cloudfront/CloudFrontDistribution.test.ts, test/monitoring/aws-cloudfront/__snapshots__/CloudFrontDistribution.test.ts.snap
Based on the internal contribution by Oriol Petit Rojo.
---
=> feat(CloudFront): add basic alarms (tps, errors)

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Closes #49
See it in action here: https://github.com/echeung-amzn/cdk-monitoring-constructs/issues/new/choose
---
=> chore: add issue templates [skip ci]

README.md
=> chore: removing not-ready-for-use banner

API.md, README.md, lib/facade/MonitoringAspect.ts, lib/facade/MonitoringFacade.ts, lib/facade/aspect-types.ts, lib/monitoring/aws-synthetics/SyntheticsCanaryMetricFactory.ts, lib/monitoring/aws-synthetics/SyntheticsCanaryMonitoring.ts, lib/monitoring/aws-synthetics/index.ts, lib/monitoring/index.ts, test/facade/MonitoringAspect.test.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-synthetics/SyntheticsCanaryMonitoring.test.ts, test/monitoring/aws-synthetics/__snapshots__/SyntheticsCanaryMonitoring.test.ts.snap
=> feat: adding monitoring support for CloudWatch Canary

API.md, lib/common/monitoring/alarms/LogLevelAlarmFactory.ts
Customer request to add FATAL into the log levels. Does not have impact in this library but it is needed in our internal facade.
---
=> feat: add FATAL log level

API.md, lib/common/alarm/AlarmFactory.ts, lib/monitoring/aws-secretsmanager/SecretsManagerMetricsPublisher.ts, test/facade/MonitoringAspect.test.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-opensearch/OpenSearchClusterMonitoring.test.ts, test/monitoring/aws-opensearch/__snapshots__/OpenSearchClusterMonitoring.test.ts.snap, test/monitoring/aws-secretsmanager/__snapshots__/SecretsManagerSecretMonitoring.test.ts.snap
Some minor updates pulled out from #83
cf. commit messages for exact changes
---
=> chore: minor cleanup

lib/monitoring/aws-cloudwatch/LogMonitoring.ts
Added logStream to the query so the end user can easily do further investigation
`npm test` passes
Fixes #85
---
=> feat: [cloudwatch][LogMonitoring] added logStream field to query

API.md, test/monitoring/SnapshotUtil.ts, test/monitoring/aws-synthetics/SyntheticsCanaryMonitoring.test.ts, test/monitoring/aws-synthetics/__snapshots__/SyntheticsCanaryMonitoring.test.ts.snap, test/monitoring/aws-wafv2/WafV2Monitoring.test.ts, test/monitoring/aws-wafv2/__snapshots__/WafV2Monitoring.test.ts.snap
Related #91 
POC, starting with WAF and CW Canaries.
---
=> chore: include widgets in snapshot tests; starting with canary and waf [skip ci]

API.md, lib/monitoring/aws-apigateway/ApiGatewayMonitoring.ts, lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.ts, test/monitoring/aws-apigateway/ApiGatewayMonitoring.test.ts, test/monitoring/aws-apigateway/__snapshots__/ApiGatewayMonitoring.test.ts.snap, test/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.test.ts, test/monitoring/aws-apigatewayv2/__snapshots__/ApiGatewayV2HttpApiMonitoring.test.ts.snap
=> feat(apigateway): add p95 latency alarms

API.md, lib/common/monitoring/alarms/ErrorAlarmFactory.ts, lib/monitoring/aws-glue/GlueJobMetricFactory.ts, lib/monitoring/aws-glue/GlueJobMonitoring.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-glue/GlueJobMonitoring.test.ts, test/monitoring/aws-glue/__snapshots__/GlueJobMonitoring.test.ts.snap
=> feat(glue): add alarms for failed/killed tasks

.projenrc.js, package.json
This _should_ help add tags on Construct Hub (https://constructs.dev/packages/cdk-monitoring-constructs).
---
=> chore: add more package keywords [skip ci]

API.md, lib/monitoring/aws-sqs/SqsQueueMonitoringWithDlq.ts
=> chore(sqs): note that incoming messages alarm does not capture messages sent to DLQ due to failed processing attempts

API.md, lib/monitoring/aws-apigateway/ApiGatewayMetricFactory.ts, lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMetricFactory.ts, lib/monitoring/aws-appsync/AppSyncMetricFactory.ts, lib/monitoring/aws-cloudfront/CloudFrontDistributionMetricFactory.ts, lib/monitoring/aws-glue/GlueJobMetricFactory.ts, lib/monitoring/aws-glue/GlueJobMonitoring.ts, lib/monitoring/aws-lambda/LambdaFunctionMetricFactory.ts, lib/monitoring/aws-opensearch/OpenSearchClusterMetricFactory.ts
=> feat: extend metric factories with custom rate computation method

API.md, lib/common/metric/MetricFactory.ts, lib/monitoring/aws-apigateway/ApiGatewayMetricFactory.ts, lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMetricFactory.ts, lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.ts, lib/monitoring/aws-appsync/AppSyncMetricFactory.ts, lib/monitoring/aws-cloudfront/CloudFrontDistributionMetricFactory.ts, lib/monitoring/aws-cloudfront/CloudFrontDistributionMonitoring.ts, lib/monitoring/aws-ec2/EC2MetricFactory.ts, lib/monitoring/aws-ec2/EC2Monitoring.ts, lib/monitoring/aws-glue/GlueJobMetricFactory.ts, lib/monitoring/aws-glue/GlueJobMonitoring.ts, lib/monitoring/aws-lambda/LambdaFunctionMetricFactory.ts, lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts, lib/monitoring/aws-opensearch/OpenSearchBackportedMetrics.ts, lib/monitoring/aws-opensearch/OpenSearchClusterMetricFactory.ts, lib/monitoring/aws-opensearch/OpenSearchClusterMonitoring.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-ec2/EC2Monitoring.test.ts, test/monitoring/aws-ec2/__snapshots__/EC2Monitoring.test.ts.snap
Cherry picks changes from `main` back to `monocdk`.
Do not auto merge this, it must be merged as rebased commits to retain the commit messages.
---
=> chore: update monocdk branch

test/monitoring/aws-acm/CertificateManagerMonitoring.test.ts, test/monitoring/aws-acm/__snapshots__/CertificateManagerMonitoring.test.ts.snap, test/monitoring/aws-apigateway/ApiGatewayMonitoring.test.ts, test/monitoring/aws-apigateway/__snapshots__/ApiGatewayMonitoring.test.ts.snap, test/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.test.ts, test/monitoring/aws-apigatewayv2/__snapshots__/ApiGatewayV2HttpApiMonitoring.test.ts.snap, test/monitoring/aws-billing/BillingMonitoring.test.ts, test/monitoring/aws-billing/__snapshots__/BillingMonitoring.test.ts.snap, test/monitoring/aws-cloudfront/CloudFrontDistribution.test.ts, test/monitoring/aws-cloudfront/__snapshots__/CloudFrontDistribution.test.ts.snap, test/monitoring/aws-cloudwatch/LogMonitoring.test.ts, test/monitoring/aws-cloudwatch/__snapshots__/LogMonitoring.test.ts.snap, test/monitoring/aws-codebuild/CodeBuildProjectMonitoring.test.ts, test/monitoring/aws-codebuild/__snapshots__/CodeBuildProjectMonitoring.test.ts.snap, test/monitoring/aws-dynamo/DynamoTableGlobalSecondaryIndexMonitoring.test.ts, test/monitoring/aws-dynamo/DynamoTableMonitoring.test.ts, test/monitoring/aws-dynamo/__snapshots__/DynamoTableGlobalSecondaryIndexMonitoring.test.ts.snap, test/monitoring/aws-dynamo/__snapshots__/DynamoTableMonitoring.test.ts.snap, test/monitoring/aws-ec2/AutoScalingGroupMonitoring.test.ts, test/monitoring/aws-ec2/__snapshots__/AutoScalingGroupMonitoring.test.ts.snap, test/monitoring/aws-ecs-patterns/Ec2ServiceMonitoring.test.ts, test/monitoring/aws-ecs-patterns/FargateServiceMonitoring.test.ts, test/monitoring/aws-ecs-patterns/__snapshots__/Ec2ServiceMonitoring.test.ts.snap, test/monitoring/aws-ecs-patterns/__snapshots__/FargateServiceMonitoring.test.ts.snap
=> chore: extend dashboard snapshots to further components

lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap
=> feat: add max iterator age for Lambda

.projen/deps.json, .projen/tasks.json, .projenrc.js, package.json, yarn.lock
chore: pin prettier types to resolve the error 
```
error TS2315: Type 'IsTuple' is not generic.
```
---
=> chore: pin prettier types [skip ci]

lib/monitoring/aws-glue/GlueJobMetricFactory.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-glue/__snapshots__/GlueJobMonitoring.test.ts.snap
=> fix(glue): fixed wrong unit for cpu/heap usage

lib/monitoring/aws-loadbalancing/NetworkLoadBalancerMonitoring.ts, test/monitoring/aws-loadbalancing/ApplicationLoadBalancerMonitoring.test.ts, test/monitoring/aws-loadbalancing/NetworkLoadBalancerMonitoring.test.ts, test/monitoring/aws-loadbalancing/__snapshots__/ApplicationLoadBalancerMonitoring.test.ts.snap, test/monitoring/aws-loadbalancing/__snapshots__/NetworkLoadBalancerMonitoring.test.ts.snap
Reported by a customer.
Also adding dashboard snapshots to the `aws-loadbalancing` tests.
---
=> fix(loadbalancing): fix duplicate summary graphs for NLBs

API.md, lib/common/widget/types.ts, lib/monitoring/custom/CustomMonitoring.ts, test/monitoring/custom/CustomMonitoring.test.ts, test/monitoring/custom/__snapshots__/CustomMonitoring.test.ts.snap
Implicitly requested via https://github.com/cdklabs/cdk-monitoring-constructs/discussions/181#discussioncomment-3040742
---
=> feat(custom): support single value graph widgets

README.md
=> chore: add detailed documentation of custom monitoring [skip ci]

API.md, lib/common/alarm/OpsItemAlarmActionStrategy.ts, lib/common/alarm/index.ts, test/common/alarm/OpsItemAlarmActionStrategy.test.ts, test/common/alarm/__snapshots__/OpsItemAlarmActionStrategy.test.ts.snap
=> feat(alarm): add OpsItem alarm action strategy

test/monitoring/aws-appsync/AppSyncMonitoring.test.ts, test/monitoring/aws-appsync/__snapshots__/AppSyncMonitoring.test.ts.snap, test/monitoring/aws-kinesis/KinesisFirehoseMonitoring.test.ts, test/monitoring/aws-kinesis/__snapshots__/KinesisFirehoseMonitoring.test.ts.snap, test/monitoring/aws-kinesisanalytics/KinesisDataAnalyticsMonitoring.test.ts, test/monitoring/aws-kinesisanalytics/__snapshots__/KinesisDataAnalyticsMonitoring.test.ts.snap, test/monitoring/aws-rds/RdsClusterMonitoring.test.ts, test/monitoring/aws-rds/__snapshots__/RdsClusterMonitoring.test.ts.snap, test/monitoring/aws-redshift/RedshiftClusterMonitoring.test.ts, test/monitoring/aws-redshift/__snapshots__/RedshiftClusterMonitoring.test.ts.snap, test/monitoring/aws-s3/S3BucketMonitoring.test.ts, test/monitoring/aws-s3/__snapshots__/S3BucketMonitoring.test.ts.snap, test/monitoring/aws-sqs/SqsQueueMonitoring.test.ts, test/monitoring/aws-sqs/SqsQueueMonitoringWithDlq.test.ts, test/monitoring/aws-sqs/__snapshots__/SqsQueueMonitoring.test.ts.snap, test/monitoring/aws-sqs/__snapshots__/SqsQueueMonitoringWithDlq.test.ts.snap, test/monitoring/aws-step-functions/StepFunctionActivityMonitoring.test.ts, test/monitoring/aws-step-functions/StepFunctionLambdaIntegrationMonitoring.test.ts, test/monitoring/aws-step-functions/StepFunctionMonitoring.test.ts, test/monitoring/aws-step-functions/StepFunctionServiceIntegrationMonitoring.test.ts, test/monitoring/aws-step-functions/__snapshots__/StepFunctionActivityMonitoring.test.ts.snap, test/monitoring/aws-step-functions/__snapshots__/StepFunctionLambdaIntegrationMonitoring.test.ts.snap, test/monitoring/aws-step-functions/__snapshots__/StepFunctionMonitoring.test.ts.snap, test/monitoring/aws-step-functions/__snapshots__/StepFunctionServiceIntegrationMonitoring.test.ts.snap
=> chore: added more monitoring dashboards into the tests [skip-ci]

.github/workflows/build.yml, .github/workflows/release.yml, .mergify.yml, .projen/tasks.json, .projenrc.js, README.md, package.json
Closes #21
Since https://github.com/aws/jsii/issues/3399 was fixed, we're now unblocked from building a Go variant.
---
=> feat: support golang

API.md, lib/common/metric/MetricFactory.ts
=> chore(docs): clarify usage of undefined in metric search [skip ci]

API.md, lib/common/alarm/CustomAlarmThreshold.ts, test/monitoring/custom/CustomMonitoring.test.ts, test/monitoring/custom/__snapshots__/CustomMonitoring.test.ts.snap
=> feat: make the minMetricSamplesToAlarm available for any alarm

lib/monitoring/aws-rds/RdsClusterMetricFactory.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-rds/__snapshots__/RdsClusterMonitoring.test.ts.snap, test/monitoring/aws-redshift/__snapshots__/RedshiftClusterMonitoring.test.ts.snap
=> fix(rds): switch connection monitor to average

lib/dashboard/widget/BitmapWidget.ts, lib/monitoring/aws-secretsmanager/SecretsManagerMetricsPublisher.ts, test/dashboard/widget/__snapshots__/BitmapWidget.test.ts.snap, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-secretsmanager/__snapshots__/SecretsManagerSecretMonitoring.test.ts.snap
Fixes #244
Reverts https://github.com/cdklabs/cdk-monitoring-constructs/pull/102
---
=> revert: use ARM_64 architecture for Lambda handler

API.md, lib/common/monitoring/alarms/UsageAlarmFactory.ts, lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts, test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts, test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap
Requested by a customer.
This does leave an `addMaxInvocationsCountAlarm` as a future possibility, but I left that out since there hasn't been ask for it (and I'm not sure if that's something that'd be actually useful). If someone wants it, please do request it!
---
=> feat(lambda): add addMinInvocationsCountAlarm

lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-apigatewayv2/__snapshots__/ApiGatewayV2HttpApiMonitoring.test.ts.snap
=> fix(apigw2): respect humanReadableName specified by user

test/monitoring/custom/CustomMonitoring.test.ts
=> chore: count created alarms in custom anomaly tests [skip ci]

API.md, lib/common/monitoring/alarms/LatencyAlarmFactory.ts, lib/monitoring/aws-dynamo/DynamoTableMonitoring.ts
=> fix: Fix latency alarm actions to adhere to the disambiguator action defaults

API.md, README.md, lib/common/monitoring/alarms/ErrorAlarmFactory.ts, lib/monitoring/aws-wafv2/WafV2Monitoring.ts, test/monitoring/aws-wafv2/WafV2Monitoring.test.ts, test/monitoring/aws-wafv2/__snapshots__/WafV2Monitoring.test.ts.snap
=> feat(waf-v2): add ability to alarm on blocked requests count and rate

CONTRIBUTING.md
=> chore(docs): add instructions on how to build and link locally [skip ci]

assets/BitmapWidgetRenderingSupport/index.js
This is an old doc from the internal days that has no relevance nowadays.
---
=> chore: remove irrelevant doc from BitmapWidgetRenderingSupport handler [skip ci]

README.md
Updating example to reflect required `statistic` prop.
---
=> chore: fix metric search example [skip ci]

README.md
Updating to reflect new major version.
---
=> chore: update README.md [skip ci]

API.md, lib/common/alarm/action/MultipleAlarmActionStrategy.ts, test/common/alarm/action/MultipleAlarmActionStrategy.test.ts
=> feat(MultipleAlarmActionStrategy): add method to get flattened actions

lib/dashboard/DynamicDashboardFactory.ts, test/dashboard/DynamicDashboardFactory.test.ts
=> fix(dashboard): fix dynamic dashboard range

README.md
Realized this was never explicitly explained in the public docs.
---
=> chore(docs): document how to override segment widgets [skip ci]

lib/monitoring/aws-opensearch/OpenSearchBackportedMetrics.ts, lib/monitoring/aws-opensearch/OpenSearchClusterMetricFactory.ts
=> chore: migrate from deprecated Statistics enum

API.md, lib/common/monitoring/alarms/LatencyAlarmFactory.ts, lib/monitoring/aws-apigateway/ApiGatewayMetricFactory.ts, lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMetricFactory.ts, lib/monitoring/aws-lambda/LambdaFunctionMetricFactory.ts, lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts, test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap
Closes #448
This also aligns how we create/present latency metrics with how we do it for other things like API Gateway.
---
=> feat(lambda): allow alarming on max latency

.vscode/settings.json, lib/monitoring/aws-loadbalancing/LoadBalancerMetricFactory.ts, test/monitoring/aws-ecs-patterns/FargateServiceMonitoring.test.ts, test/monitoring/aws-ecs-patterns/__snapshots__/FargateServiceMonitoring.test.ts.snap
Fixes #476
This is an alternative to PR #477 without a breaking API change.
---
=> feat(ecs-patterns): improve ALB/NLB type guards

lib/common/url/AwsConsoleUrlFactory.ts, test/common/url/AwsConsoleUrlFactory.test.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-sqs/__snapshots__/SqsQueueMonitoring.test.ts.snap, test/monitoring/aws-sqs/__snapshots__/SqsQueueMonitoringWithDlq.test.ts.snap
=> fix(sqs): update console URL

API.md, lib/monitoring/aws-cloudwatch/LogMonitoring.ts, test/monitoring/aws-cloudwatch/LogMonitoring.test.ts, test/monitoring/aws-cloudwatch/__snapshots__/LogMonitoring.test.ts.snap
=> feat(logs): add addMaxIncomingLogsAlarm

.projen/tasks.json, .projenrc.ts, API.md, lib/monitoring/aws-ec2/EC2MetricFactory.ts, lib/monitoring/aws-kinesisanalytics/KinesisDataAnalyticsMetricFactory.ts, lib/monitoring/aws-lambda/LambdaFunctionEnhancedMetricFactory.ts, lib/monitoring/aws-lambda/LambdaFunctionMetricFactory.ts, lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts, lib/monitoring/aws-secretsmanager/SecretsManagerMetricFactory.ts, lib/monitoring/aws-secretsmanager/SecretsManagerMonitoring.ts, lib/monitoring/fluentbit/FluentBitMetricFactory.ts, test/facade/MonitoringFacade.test.ts, test/facade/__snapshots__/MonitoringFacade.test.ts.snap
This is a continuation of #534, but it includes breaking changes to some existing metric factories' constructor API contracts.
Also includes some minor private method renaming for consistency and a basic facade test, pulled out from #533.
---
=> feat!: update more MetricFactory classes to extend base

lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/facade/__snapshots__/MonitoringFacade.test.ts.snap, test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap
Fixes regression from #574.
---
=> fix(lambda): add dashboard widgets properly

lib/monitoring/aws-cloudwatch/CloudWatchLogsMetricFactory.ts, test/monitoring/aws-cloudwatch/__snapshots__/LogMonitoring.test.ts.snap
=> fix(cloudwatch): use correct metric statistic for IncomingLogEvents

.projen/deps.json, .projen/tasks.json, .projenrc.ts, package.json
Extracting from #594 since it wasn't really relevant.
The problem with the types being incompatible has been long resolved.
---
=> chore: remove explicit @types/prettier override

API.md, lib/common/alarm/action/LambdaAlarmActionStrategy.ts, lib/common/alarm/action/index.ts, test/common/alarm/action/LambdaAlarmActionStrategy.test.ts, test/common/alarm/action/__snapshots__/LambdaAlarmActionStrategy.test.ts.snap
=> feat: support Lambda actions

API.md, lib/common/monitoring/alarms/LatencyAlarmFactory.ts, lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts, test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts, test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap
=> feat(lambda): allow latency alarms to be based on function timeout

lib/dashboard/widget/BitmapWidget.ts, lib/monitoring/aws-secretsmanager/SecretsManagerMetricsPublisher.ts, test/dashboard/widget/__snapshots__/BitmapWidget.test.ts.snap, test/facade/__snapshots__/MonitoringAspect.test.ts.snap, test/monitoring/aws-secretsmanager/__snapshots__/SecretsManagerSecretMonitoring.test.ts.snap
=> feat: replace deprecated logRetention usages with explicit Lambda log groups

API.md, README.md, lib/common/url/AwsConsoleUrlFactory.ts, lib/facade/MonitoringFacade.ts, lib/monitoring/aws-osis/OpenSearchIngestionPipelineMetricFactory.ts, lib/monitoring/aws-osis/OpenSearchIngestionPipelineMonitoring.ts, lib/monitoring/aws-osis/index.ts, lib/monitoring/index.ts, test/common/url/AwsConsoleUrlFactory.test.ts, test/monitoring/aws-osis/OpenSearchIngestionPipelineMonitoring.test.ts, test/monitoring/aws-osis/__snapshots__/OpenSearchIngestionPipelineMonitoring.test.ts.snap
=> feat(osis): add monitoring for OpenSearch Ingestion pipelines

API.md, README.md, lib/common/url/AwsConsoleUrlFactory.ts, lib/facade/MonitoringFacade.ts, lib/monitoring/aws-opensearchserverless/OpenSearchServerlessIndexMetricFactory.ts, lib/monitoring/aws-opensearchserverless/OpenSearchServerlessIndexMonitoring.ts, lib/monitoring/aws-opensearchserverless/OpenSearchServerlessMetricFactory.ts, lib/monitoring/aws-opensearchserverless/OpenSearchServerlessMonitoring.ts, lib/monitoring/aws-opensearchserverless/index.ts, lib/monitoring/index.ts, test/common/url/AwsConsoleUrlFactory.test.ts, test/monitoring/aws-opensearchserverless/OpenSearchServerlessIndexMonitoring.test.ts, test/monitoring/aws-opensearchserverless/OpenSearchServerlessMonitoring.test.ts, test/monitoring/aws-opensearchserverless/__snapshots__/OpenSearchServerlessIndexMonitoring.test.ts.snap, test/monitoring/aws-opensearchserverless/__snapshots__/OpenSearchServerlessMonitoring.test.ts.snap
=> feat(opensearchserverless): add monitoring for Collections and Indices
