cdklabs/cdk-monitoring-constructs

.projenrc.js
package.json

Fix homepage github repo link since the current format is not supported on pypi

chore: fix homepage link

---

.npmignore
.projenrc.js
package.json

Partially addresses #18
Verified that tarball (`dist/js/cdk-monitoring-constructs@0.0.0.jsii.tgz`) doesn't include TS files anymore.

chore: exclude TS files from final tarball

---

assets/BitmapWidgetRenderingSupport/index.js
assets/SecretsManagerMetricsPublisher/index.js
test/dashboard/widget/__snapshots__/BitmapWidget.test.ts.snap
test/monitoring/aws-secretsmanager/__snapshots__/SecretsManagerSecretMonitoring.test.ts.snap

Partially addresses #18
We don't necessarily need JSII (and therefore TS) to process these.

chore: convert Lambda handlers to vanilla JS

---

API.md
lib/common/alarm/MultipleAlarmActionStrategy.ts
lib/common/alarm/index.ts
test/common/alarm/MultipleAlarmActionStrategy.test.ts
test/common/alarm/__snapshots__/MultipleAlarmActionStrategy.test.ts.snap

Users will be able to use `multipleActions(action1, action2, etc)` to add multiple actions to a single alarm.

feat(actions): add feature to add multiple actions to an alarm

---

API.md
README.md
lib/facade/aspect-types.ts

chore: Update readme with scope monitoring
Also making the `enabled` prop optional.
follow up to #34

chore: Update reamdme with scope monitoring

---

.github/workflows/upgrade-main.yml
.projenrc.js

This is up for debate, but daily dependency updates (and therefore new releases) seem like overkill. 
This also increases the risk/likelihood of bringing in new malicious dependency versions (e.g., what happened with `colors`).

chore: only run upgrade deps workflow once weekly [skip ci]

---

lib/monitoring/custom/CustomMonitoring.ts

Avoids noisy diffs when doing `cdk diff`, e.g.:
```
Resources
[~] AWS::CloudWatch::Dashboard Monitoring/Dashboards/Dashboard MonitoringDashboardsDashboard7D19B914
└─ [~] DashboardBody
└─ [~] .Fn::Join:
└─ @@ -1,7 +1,7 @@
[ ] [
[ ]  "",
[ ]  [
[-]    "{\"start\":\"-P7D\",\"periodOverride\":\"inherit\",\"widgets\":[{\"type\":\"text\",\"width\":24,\"height\":2,\"x\":0,\"y\":0,\"properties\":{\"markdown\":\"| Info\\n|---\\n| AWS / Lambda / Test\"}},{\"type\":\"text\",\"width\":24,\"height\":1,\"x\":0,\"y\":2,\"properties\":{\"markdown\":\"# Custom metrics\"}},{\"type\":\"text\",\"width\":24,\"height\":1,\"x\":0,\"y\":3,\"properties\":{\"markdown\":\"### Test-CDK\"}},{\"type\":\"text\",\"width\":24,\"height\":1,\"x\":0,\"y\":4,\"properties\":{\"markdown\":\"? My custom monitor on some …
```

fix: avoid noisy dashboard diffs with custom monitoring

---

lib/monitoring/custom/CustomMonitoring.ts
test/monitoring/custom/CustomMonitoring.test.ts

Instead of silently dropping the anomaly detection alarm config.
---

fix(custom): explicitly throw error when trying to add both a regular and anomaly detection alarm

---

.github/workflows/release.yml
.projenrc.js

I don't have a particularly good way of testing this.
Based on:
- https://github.com/cdklabs/construct-hub-webapp/pull/501/files
Using:
- https://github.com/bruceadams/get-release
- https://github.com/slackapi/slack-github-action
The webhook secret has already been added to the repo.
---

chore: send notification to Slack on release [skip ci]

---

.github/workflows/release.yml
.projenrc.js

The previous attempted [failed](https://github.com/cdklabs/cdk-monitoring-constructs/runs/5530778333?check_suite_focus=true) since the action tries to get a release for a given tag, except the workflow is actually triggered on push, not by a tag.
This switches to [cardinalby/git-get-release-action](https://github.com/cardinalby/git-get-release-action), which defaults to getting a release based on the current commit SHA.
---

chore: use action to get release by current SHA for Slack notification [skip ci]

---

API.md
lib/common/monitoring/alarms/LatencyAlarmFactory.ts
lib/monitoring/aws-apigateway/ApiGatewayMetricFactory.ts
lib/monitoring/aws-apigateway/ApiGatewayMonitoring.ts
lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMetricFactory.ts
lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-apigateway/ApiGatewayMonitoring.test.ts
test/monitoring/aws-apigateway/__snapshots__/ApiGatewayMonitoring.test.ts.snap
test/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.test.ts
test/monitoring/aws-apigatewayv2/__snapshots__/ApiGatewayV2HttpApiMonitoring.test.ts.snap

Introduces latency factory methods with latency type parameter in Api Gateway. It will be useful for creating trimmed-mean alarms, etc.
Closes #65
Closes #47
---

feat(apigateway): support trimmed stats and latency graph configuration

---

README.md

Closes #26
Might as well defer to those websites for more comprehensive options on how to install the dependencies.
I retained the NPM instructions since it's the most common usecase.
---

chore: update installation instructions [skip ci]

---

API.md
lib/monitoring/aws-dynamo/DynamoTableMetricFactory.ts

Fixes #48
This should unblock the CDK v2 upgrade.
If we want to support the other operations, we can add more metrics/alarms configurations for those.
---

fix(dynamo): limit metricSystemErrorsCount to previously defined operations

---

API.md
lib/monitoring/aws-ec2/EC2MetricFactory.ts
lib/monitoring/aws-ec2/EC2Monitoring.ts
test/monitoring/aws-ec2/EC2Monitoring.test.ts
test/monitoring/aws-ec2/__snapshots__/EC2Monitoring.test.ts.snap

Allows users to specify instance IDs in the EC2 monitoring and combine them with ASG property.
Fixes #43 
---

feat(ec2): allow users to specify EC2 instance IDs to monitor

---

lib/common/metric/MetricFactory.ts
lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.ts
lib/monitoring/aws-cloudfront/CloudFrontDistributionMonitoring.ts
lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts
lib/monitoring/aws-opensearch/OpenSearchClusterMonitoring.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap

Found some TPS axes that had invalid (Count-based) label.
---

fix: fixed TPS widget axis labels

---

API.md
lib/monitoring/aws-opensearch/OpenSearchBackportedMetrics.ts
lib/monitoring/aws-opensearch/OpenSearchClusterMetricFactory.ts
lib/monitoring/aws-opensearch/OpenSearchClusterMonitoring.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap

As reported internally.
The correct metric name should be `ClusterIndexWritesBlocked` according to https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html
---

fix(elasticsearch/opensearch): fix ClusterIndexWritesBlocked metric name

---

.github/workflows/upgrade-main.yml
.github/workflows/upgrade-monocdk.yml
.projenrc.js

Since we're now in maintenance mode for monocdk (see #129), we no longer want weekly updates/releases.
We can still manually invoke the workflow if needed.
---

chore: disable weekly dependency updates for monocdk branch

---

API.md
lib/common/alarm/MultipleAlarmActionStrategy.ts

Made MultipleAlarmActionStrategy.actions public so we can process the actions internally.
---

feat: make MultipleAlarmActionStrategy.actions public

---

API.md
README.md
lib/monitoring/aws-cloudfront/CloudFrontDistributionMetricFactory.ts
lib/monitoring/aws-cloudfront/CloudFrontDistributionMonitoring.ts
test/monitoring/aws-cloudfront/CloudFrontDistribution.test.ts
test/monitoring/aws-cloudfront/__snapshots__/CloudFrontDistribution.test.ts.snap

As pointed out by a user, these metrics are not available by default, so it won't always be relevant.
This is kept as enabled by default to preserve the existing behaviour.
---

feat(cloudfront): allow disabling dashboard widgets based on additional metrics

---

lib/dashboard/DefaultDashboardFactory.ts
test/dashboard/DefaultDashboardFactory.test.ts
test/dashboard/__snapshots__/DefaultDashboardFactory.test.ts.snap

We currently have this logic in the internal extension library, but this should be enforced at the core library level.
---

fix(dashboards): enforce non-empty dashboardNamePrefix

---

API.md
lib/dashboard/DefaultDashboardFactory.ts
test/dashboard/DefaultDashboardFactory.test.ts

This is useful if you want to conditionally create any constructs based on the existence of dashboards without necessarily checking the input props.
---

feat(dashboards): expose anyDashboardCreated from DefaultDashboardFactory

---

API.md
lib/monitoring/aws-dynamo/DynamoTableMetricFactory.ts
lib/monitoring/aws-dynamo/DynamoTableMonitoring.ts
test/monitoring/aws-dynamo/DynamoTableMonitoring.test.ts
test/monitoring/aws-dynamo/__snapshots__/DynamoTableMonitoring.test.ts.snap

Some metrics do not make sense for on-demand dynamo DB table. Therefore, including a new billing mode parameter and adjusting the dashboard contents for the same.
Related: #185
---

feat(dynamodb): simplify dashboard for PAY_PER_REQUEST tables

---

API.md
lib/common/alarm/AlarmFactory.ts
lib/common/alarm/IAlarmAnnotationStrategy.ts
test/common/alarm/AlarmFactory.test.ts

Allow users to override 1) color 2) label 3) visibility of the alarm annotation.
---

feat: allow users to customize alarm annotation properties

---

.projenrc.js
package.json

Addressing [build failure](https://github.com/cdklabs/cdk-monitoring-constructs/runs/7810695971?check_suite_focus=true).
---

fix: use proper module name for go module

---

README.md

It was noted that the file is too big for GitHub to render nicely, so there isn't much benefit to linking to it.
Users should instead browse the nicely rendered docs on constructs.dev.
---

chore(docs): remove link to API.md from README.md [skip ci]

---

API.md
lib/common/alarm/AlarmFactory.ts
test/common/alarm/AlarmFactory.test.ts

Actions are resolved in the following order:
1. `actionOverride` from that alarm's props, if present
2. `disambiguatorAction` from the facade's defaults, if present (**new**)
3. Default `action` from the facade's defaults, if present
4. Finally fallbacks to a no-op action
---

feat(facade): add ability to specify default actions by alarm disambiguator

---

API.md
lib/monitoring/custom/CustomMonitoring.ts
test/monitoring/custom/CustomMonitoring.test.ts
test/monitoring/custom/__snapshots__/CustomMonitoring.test.ts.snap

Resolves #242 
To keep the add to summary naming consistent the new property has been added to CustomMetricGroup.
---

feat: deprecate `important` property in favor of `addToSummaryDashboard` in CustomMetricGroup

---

API.md
lib/dashboard/widget/HeaderWidget.ts
lib/dashboard/widget/MonitoringHeaderWidget.ts
test/dashboard/widget/HeaderWidget.test.ts
test/dashboard/widget/MonitoringHeaderWidget.test.ts
test/dashboard/widget/__snapshots__/HeaderWidget.test.ts.snap
test/dashboard/widget/__snapshots__/MonitoringHeaderWidget.test.ts.snap

Adding support for description. Later can be used to add generic description parameters to every monitoring props (user ask).
---

feat(widget): header widget supports adding description

---

API.md
lib/monitoring/aws-appsync/AppSyncMetricFactory.ts
test/monitoring/aws-appsync/AppSyncMonitoring.test.ts
test/monitoring/aws-appsync/__snapshots__/AppSyncMonitoring.test.ts.snap

To stay consistent with other parts of the library.
---

fix(appsync): allow imported `IGraphqlApi` resources

---

API.md
lib/monitoring/custom/CustomMonitoring.ts
test/monitoring/custom/CustomMonitoring.test.ts
test/monitoring/custom/__snapshots__/CustomMonitoring.test.ts.snap

It's confusing that the top-level `addToSummaryDashboard` didn't do anything. This is now the lowest-precedence way to add things to the summary dashboard. This still defaults to `false` to maintain existing behaviour.
---

feat(custom): use addToSummaryDashboard from CustomMonitoringProps if not specified in metric groups

---

API.md
lib/common/monitoring/alarms/UsageAlarmFactory.ts
yarn.lock

Fixes # Addition of multiple alarms from the sameclass
UsageAlarmFactory is creating same AlarmSuffix  for every alarm that is being added in a class which leads to creation of duplicate alarms, as they have same name. This fix appends the UsageType to the alarm name thus allowing users to create alarm on avg, p50,p90... all metrics from the same class.
---

fix(UsageAlarmFactory): allowing addition of multiple alarms from the same class

---

.projen/deps.json
.projen/tasks.json
.projenrc.js
API.md
README.md
lib/facade/MonitoringAspect.ts
lib/monitoring/aws-appsync/AppSyncMetricFactory.ts
package.json
test/assets/schema.graphql
test/common/alarm/__snapshots__/OpsItemAlarmActionStrategy.test.ts.snap
test/common/metric/__snapshots__/MetricFactory.test.ts.snap
test/dashboard/widget/__snapshots__/HeaderWidget.test.ts.snap
test/dashboard/widget/__snapshots__/KeyValueTableWidget.test.ts.snap
test/dashboard/widget/__snapshots__/MonitoringHeaderWidget.test.ts.snap
test/facade/MonitoringAspect.test.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-acm/__snapshots__/CertificateManagerMonitoring.test.ts.snap
test/monitoring/aws-apigateway/__snapshots__/ApiGatewayMonitoring.test.ts.snap
test/monitoring/aws-appsync/AppSyncMonitoring.test.ts
test/monitoring/aws-appsync/__snapshots__/AppSyncMonitoring.test.ts.snap
test/monitoring/aws-docdb/__snapshots__/DocumentDbMonitoring.test.ts.snap
test/monitoring/aws-ec2/__snapshots__/AutoScalingGroupMonitoring.test.ts.snap
test/monitoring/aws-ecs-patterns/__snapshots__/Ec2ServiceMonitoring.test.ts.snap
test/monitoring/aws-ecs-patterns/__snapshots__/FargateServiceMonitoring.test.ts.snap
test/monitoring/aws-ecs-patterns/__snapshots__/misc.test.ts.snap
test/monitoring/aws-loadbalancing/__snapshots__/ApplicationLoadBalancerMonitoring.test.ts.snap
test/monitoring/aws-loadbalancing/__snapshots__/NetworkLoadBalancerMonitoring.test.ts.snap
test/monitoring/aws-opensearch/__snapshots__/OpenSearchClusterMonitoring.test.ts.snap
test/monitoring/aws-step-functions/__snapshots__/StepFunctionMonitoring.test.ts.snap
yarn.lock

BREAKING CHANGE: requires aws-cdk-lib@^2.60.0
The AppSync module was promoted to stable in https://github.com/aws/aws-cdk/releases/tag/v2.60.0. The peer dependency change is a breaking change, so this bumps this library up to v2.
---

feat!: use stable appsync module

---

lib/monitoring/aws-glue/GlueJobMetricFactory.ts

Fixes the following error:
```
Error: Resolution error: Resolution error: Resolution error: Cannot have two different metrics share the same id ('killed') in one Alarm or Graph. Rename one of them..
```
---

fix(glue): fix incorrect duplicate metric ID

---

API.md
README.md
lib/monitoring/aws-cloudwatch/CloudWatchLogsMetricFactory.ts
lib/monitoring/aws-cloudwatch/LogMonitoring.ts
lib/monitoring/aws-cloudwatch/index.ts
test/monitoring/aws-cloudwatch/LogMonitoring.test.ts
test/monitoring/aws-cloudwatch/__snapshots__/LogMonitoring.test.ts.snap

Add ability to alarm on minimum number from `IncomingLogEvents` metric for a given CloudWatch log group. This is useful for detecting issues that would surface as missing incoming logs as a symptom (e.g., improper permissions, service outage/configuration issue, etc.).
All available metrics: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch-Logs-Monitoring-CloudWatch-Metrics.html
---

feat(cloudwatch): add addMinIncomingLogsAlarm

---

API.md
lib/common/metric/MetricFactory.ts
test/common/metric/MetricFactory.test.ts
test/common/metric/__snapshots__/MetricFactory.test.ts.snap

This lets me create cross-account and cross-region monitoring. Currently only the current account is supported.
My PR adds these parameters at the *global level* because I didn't want to go through every resource and add these extra parameters. This creates a limitation where an instance of `MonitoringFacade` would refer only to those specific region/accounts.
This is good enough for me though, so please advise if it's not desired.
---

feat: Add region and account parameters as optional global defaults

---

API.md
lib/common/alarm/AlarmFactory.ts
lib/common/alarm/AlarmNamingStrategy.ts
lib/common/alarm/IAlarmNamingStrategy.ts
lib/common/alarm/index.ts
test/common/alarm/AlarmFactory.test.ts

Making the AlarmNamingStrategy configurable. My team wants to add the disambiguator to the alarm dedupe string. This requires custom logic for generating the deduplication string, which is why we want to be able to override this class's functionality.

feat(alarm): Make AlarmNamingStrategy customizable

---

API.md
lib/monitoring/aws-wafv2/WafV2MetricFactory.ts
test/monitoring/aws-wafv2/WafV2Monitoring.test.ts
test/monitoring/aws-wafv2/__snapshots__/WafV2Monitoring.test.ts.snap

The metrics specifically have a `Region` dimension when using a regional Web ACL (as opposed to a global Cloudfront one that lacks that dimension).
Also explicitly specify a `name` for the test resources, as it seems like `CfnWebACL` doesn't return a `name` if you don't set it.
---

fix(waf-v2): include Region dimension if specified

---

lib/common/monitoring/alarms/UsageAlarmFactory.ts
test/monitoring/aws-cloudwatch/__snapshots__/LogMonitoring.test.ts.snap
test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap

`LESS_THAN_LOWER_THRESHOLD` is for:
```
* Specified statistic is lower than the anomaly model band.
* Used only for alarms based on anomaly detection models
```
...which is not what it was being used for.
---

fix: use LESS_THAN_THRESHOLD for addMinUsageCountAlarm

---

lib/facade/MonitoringFacade.ts

Cross account dashboards have been added in https://github.com/cdklabs/cdk-monitoring-constructs/pull/311, but I noticed that the URLs would try to open the AWS Console in the wrong account.
This PR fixes that.
---

fix: Use correct account when creating Console URLs in the case of cross-account monitoring

---

.vscode/launch.json

I was asked how to debug the unit tests. This adds a task for use in VSCode so that you can use the debugger with test files (i.e. set breakpoints, stepping through, looking at call stacks and variable states, etc.).
Based on the task from https://mattmazzola.medium.com/how-to-debug-jest-tests-with-vscode-48f003c7cb41
---

chore: add VSCode launch task for debugging Jest tests [skip ci]

---

README.md

`monitorWebApplicationFirewallAcl` has been renamed to `monitorWebApplicationFirewallAclV2` in previous versions probably not still shows the wrong function name in docs
---

chore(docs): fix incorrect WAF monitoring function name in README [skip ci]

---

lib/facade/MonitoringFacade.ts

Fixes #357
This was unintentionally changed during [this refactoring](https://github.com/cdklabs/cdk-monitoring-constructs/commit/6e04b202de62afb056f2fe1ef89bfda10da6d726#diff-03751236dd3f86d2e1421165630d186616c9ca23c203b86ab195b36c5f1022f2) in between v3.0.4 and v3.0.5.
---

fix(dashboards): use correct scope for default DashboardFactory

---

lib/monitoring/aws-dynamo/DynamoTableGlobalSecondaryIndexMetricFactory.ts
test/monitoring/aws-dynamo/__snapshots__/DynamoTableGlobalSecondaryIndexMonitoring.test.ts.snap

Fixes #362
Results in a dashboard widget with a source like:
```
{
"view": "timeSeries",
"title": "Read Capacity",
"region": "us-east-1",
"metrics": [
[ { "label": "Consumed", "expression": "consumed_rcu_sum/PERIOD(consumed_rcu_sum)", "region": "us-east-1" } ],
[ "AWS/DynamoDB", "ConsumedReadCapacityUnits", "GlobalSecondaryIndexName", "SampleTable2-GSI", "TableName", "SampleTable2", { "stat": "Sum", "visible": false, "id": "consumed_rcu_sum", "region": "us-east-1" } ],
[ ".", "ProvisionedReadCapacityUnits", ".", ".", ".", ".", { "label": "Provisioned", "stat": "Sum", "region": "us-east-1" } ]
],
"yAxis": {
"left": {
"min": 0,
"label": "Count",
"showUnits": false
}
},
"timezone": "UTC"
}
```
---
_By submitting this pull request, I confirm that my contribution is made under the terms of the …

fix(dynamo): divide GSI consumed RCU/WCU metrics by period

---

.projen/tasks.json
.projenrc.js
API.md
lib/dashboard/DynamicDashboardSegment.ts
lib/dashboard/SingleWidgetDashboardSegment.ts
lib/facade/MonitoringFacade.ts
test/facade/MonitoringFacade.test.ts

This change fixes a couple things with the dynamic dashboard functionality that was introduced in https://github.com/cdklabs/cdk-monitoring-constructs/commit/d118a6e0f5c788e9d986d12277a5a3ca541b8cca
1. `SingleWidgetDashboardSegment` was accepting ctor params to control dashboard visibility which conflicted with the overrideProps uses elsewhere to control the same. This change removes those params in favor of having consumers control this using overrideProps.
2. Fixes some issues in the `StaticSegmentDynamicAdapter` logic which were impacting backwards compatibility.
3. Introduces a new test to provide better coverage for the above two issues.
---

fix(dashboards)!: handle dynamic dashboards in SingleWidgetDashboardSegment

---

.github/workflows/release.yml
.projenrc.js

Addresses the warning:
> 
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: slackapi/slack-github-action@v1.18.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Example run with warning: https://github.com/cdklabs/cdk-monitoring-constructs/actions/runs/5148341475
---

chore: bump slackapi/slack-github-action [skip ci]

---

API.md
lib/common/monitoring/alarms/KinesisAlarmFactory.ts
lib/monitoring/aws-kinesis/KinesisFirehoseMetricFactory.ts
lib/monitoring/aws-kinesis/KinesisFirehoseMonitoring.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-kinesis/KinesisFirehoseMonitoring.test.ts
test/monitoring/aws-kinesis/__snapshots__/KinesisFirehoseMonitoring.test.ts.snap

- adding the following alarm for firehose streams
- IncomingBytesExceedThresholdAlarm
- IncomingRecordsExceedThresholdAlarm
- IncomingPutRequestsExceedThresholdAlarm
- updated `metricIncomingRecordCount` name from `"Incoming"` to `"Incoming (Records)"` to be consistent with `metricIncomingPutRequests` and `metricIncomingBytes`
Successfully executed the following command
```
yarn test
yarn build
yarn package-all
```
---

feat(kinesis): add ability to create alarms for firehose streams approaching traffic limit quota

---

API.md
README.md
lib/common/monitoring/alarms/SecretsManagerAlarmFactory.ts
lib/common/monitoring/alarms/index.ts
lib/facade/MonitoringFacade.ts
lib/monitoring/aws-secretsmanager/SecretsManagerMetricFactory.ts
lib/monitoring/aws-secretsmanager/SecretsManagerMonitoring.ts
lib/monitoring/aws-secretsmanager/index.ts
test/monitoring/aws-secretsmanager/SecretsManagerMonitoring.test.ts
test/monitoring/aws-secretsmanager/__snapshots__/SecretsManagerMonitoring.test.ts.snap

Added new Secrets Manager Monitor to support Account-Level Secrets Count. This includes a new SecretsManagerMonitor, a new SecretsManagerMetricsFactory, and a new SecretsManagerAlarmFactory. There is alarm support for Min/Max Secrets count and change in secrets count.
Closes #137
---

feat(SecretsManager): Add support for secrets count metric

---

API.md
lib/monitoring/aws-apigateway/ApiGatewayMetricFactory.ts
test/monitoring/aws-apigateway/ApiGatewayMonitoring.test.ts
test/monitoring/aws-apigateway/__snapshots__/ApiGatewayMonitoring.test.ts.snap

As of 2.90.0 aws-cdk now supports restApiName in the IRestApi interface. By using this interface it becomes possible for developers to monitor APIGateway without the need to reference the actual RestAPI.
Related commit: https://github.com/aws/aws-cdk/commit/3bf1361e20e2b2d497fcc2197fa45dac91e7eee3
---

feat(apigateway): allow using IRestApi instead of RestApiBase

---

lib/facade/MonitoringAspect.ts
test/facade/MonitoringAspect.test.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap

fix(apigateway): use deployed stage's name when using MonitoringAspect

---

README.md

Fixes typo in documentation in README.md
---

fix: correct typo in README.md [skip ci]

---

assets/BitmapWidgetRenderingSupport/index.js
lib/dashboard/widget/BitmapWidget.ts
test/dashboard/widget/__snapshots__/BitmapWidget.test.ts.snap

Addresses the first of two Lambda functions for #393.
Tested successfully in a dev account configured with bitmap dashboards (i.e. with `renderingPreference: DashboardRenderingPreference.INTERACTIVE_AND_BITMAP)`.
---

feat: upgrade bitmap widget rendering Lambda to Node.js 18

---

API.md
lib/common/alarm/CustomAlarmThreshold.ts
test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts
test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap

Addresses a gap where these props weren't customizable via typical facade usage.
---

feat: allow overriding annotation properties from CustomAlarmThreshold

---

API.md
lib/monitoring/aws-kinesis/KinesisDataStreamMetricFactory.ts
lib/monitoring/aws-kinesis/KinesisDataStreamMonitoring.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-kinesis/__snapshots__/KinesisDataStreamMonitoring.test.ts.snap

Fixes https://github.com/cdklabs/cdk-monitoring-constructs/issues/418
---

fix(kinesis): change Provisioned Capacity Exceeded metric's Y axis label to CountAxisFromZero

---

CONTRIBUTING.md
README.md
SECURITY.md

Adding doc in standardized GitHub location so it's easily discoverable in the main project view.
---

chore: add security policy doc [skip ci]

---

API.md
lib/common/alarm/AlarmFactory.ts
lib/common/alarm/CustomAlarmThreshold.ts
lib/dashboard/widget/BitmapWidget.ts
lib/monitoring/aws-secretsmanager/SecretsManagerMetricsPublisher.ts
test/dashboard/widget/__snapshots__/BitmapWidget.test.ts.snap
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-secretsmanager/__snapshots__/SecretsManagerSecretMonitoring.test.ts.snap

Some minor doc updates to reword or remove things that don't make sense in the context of the public library.
---

chore: update some docs

---

API.md
lib/common/monitoring/alarms/UsageAlarmFactory.ts
lib/monitoring/aws-elasticache/ElastiCacheClusterMetricFactory.ts
lib/monitoring/aws-elasticache/ElastiCacheClusterMonitoring.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-elasticache/ElastiCacheClusterMonitoring.test.ts
test/monitoring/aws-elasticache/__snapshots__/ElastiCacheClusterMonitoring.test.ts.snap

Monitor engine utilization by default for Redis ElastiCache clusters. Optionally add alarms based on this metric.
Redis is single-threaded and the Redis thread's utilization is available via the EngineCPUUtilization metric. This metric provides visibility into the load of the redis process itself.
---

feat(elasticache): monitor Redis engine CPU utilization

---

API.md
README.md
lib/common/monitoring/alarms/AuroraAlarmFactory.ts
lib/common/monitoring/alarms/UsageAlarmFactory.ts
lib/common/monitoring/alarms/index.ts
lib/facade/IMonitoringAspect.ts
lib/facade/MonitoringAspect.ts
lib/facade/MonitoringFacade.ts
lib/monitoring/aws-rds/AuroraClusterMonitoring.ts
lib/monitoring/aws-rds/RdsClusterMetricFactory.ts
lib/monitoring/aws-rds/index.ts
test/monitoring/aws-rds/AuroraClusterMonitoring.test.ts
test/monitoring/aws-rds/__snapshots__/AuroraClusterMonitoring.test.ts.snap

Added new AuroraCluster Monitoring with Aurora specific metrics/alarms.
Fixes #217
---

feat(rds): add support for Aurora Serverless Clusters

---

API.md
lib/common/alarm/AlarmFactory.ts
lib/common/alarm/IAlarmAnnotationStrategy.ts
test/common/alarm/AlarmFactory.test.ts

Fixes #452
Currently, when using `minMetricSamplesToAlarm` the number of samples is evaluated for a different period than the main alarm. This makes monitoring sensitive to false positives as not every breaching datapoint must have sufficient number of samples (see #452 for more details).
Moreover, the current approach for adjusting alarms to respect `minMetricSamplesToAlarm` is to create 2 extra alarms - one for `NoSamples` and one for a top-level composite. Each of these monitors incurs extra costs ($0.10 for `NoSamples` monitor and $0.50 for the Composite, see https://aws.amazon.com/cloudwatch/pricing/ for reference). This means that using `minMetricSamplesToAlarm` increases the cost from $0.10 per alarm to $0.70 per alarm ($0.60 of overhead!).
It's possible to use Math Expression …

feat(alarm): add minSampleCountToEvaluateDatapoint

---

API.md
lib/common/alarm/AlarmFactory.ts
lib/common/alarm/CustomAlarmThreshold.ts
test/common/alarm/AlarmFactory.test.ts
test/monitoring/custom/CustomMonitoring.test.ts
test/monitoring/custom/__snapshots__/CustomMonitoring.test.ts.snap

Fixes #452
Follow up to https://github.com/cdklabs/cdk-monitoring-constructs/pull/453:
* (feat) Exposing the new `minSampleCountToEvaluateDatapoint` through CustomMonitoring 
* (fix) Fixing the `minSampleCountToEvaluateDatapoint` MathExpression's period as it defaults to 5 minutes. This didn't come up during testing as I tested it using 5 minute period. Apparently, if we don't set the period on MathExpression explicitly, it overrides all child metrics to 5 minute, [reference](https://github.com/aws/aws-cdk/blob/db21fefc2dc76eb4ff306fa41652ab6a6cc95e42/packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts#L606). To avoid similar situations in the future, extended the unit test to cover custom periods.
---
_By submitting this pull request, I confirm that my contribution is made under the terms …

feat(alarm): add minSampleCountToEvaluateDatapoint to CustomMonitoring

---

API.md
lib/facade/MonitoringFacade.ts

Including returning the facade when calling addDynamicSegment to allow chaining similar to addSegment.
Also intended to clarify the significance of needing to subclass `Monitoring` for some of the alarm-related methods to work.
---

fix: minor facade cleanup

---

.projen/deps.json
.projen/tasks.json
.projenrc.ts
API.md
README.md
lib/facade/MonitoringAspect.ts
lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMetricFactory.ts
package.json
test/facade/MonitoringAspect.test.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.test.ts
yarn.lock

BREAKING CHANGE: requires aws-cdk-lib@^2.112.0
The API Gateway v2 modules were promoted to stable in https://github.com/aws/aws-cdk/releases/tag/v2.112.0.
---

feat!: use stable api-gatewayv2 module

---

API.md
lib/common/alarm/AlarmFactory.ts
test/common/alarm/AlarmFactory.test.ts

As discussed outside of Github, this PR adds MathExpression support for minSampleCountToEvaluateDatapoint under the following circumstances:
1. If the MathExpression only has a single metric, convert to a sampleCount metric and use it for the minSampleCount
2. If there are more than one metric, rely on the new optional `sampleCountMetricId` prop to determine which existing metric in the MathExpression should be used for the sampleCount
3. Otherwise, throw an `Error`

feat(alarm): add MathExpression support for minSampleCountToEvaluateDatapoint

---

API.md
lib/facade/MonitoringFacade.ts

Also allows chaining after monitorScope.
Fixes #284
This is actually what the generated types have anyway.
---

feat: explicitly declare return types for facade methods

---

API.md
lib/common/monitoring/alarms/UsageAlarmFactory.ts

The existing API results in conflicts due to the identical `alarmNameSuffix`s.
This PR adds new replacement APIs to avoid changing existing alarm names and better aligning the interface's prop naming.
---

feat(UsageAlarmFactory): allow creating min/max count usage alarms without conflicting alarm names

---

lib/common/widget/axis.ts

Useful for graphs where it'd go up to 100% but we want to see dips in it that might otherwise be difficult to see if the axis was 0 to 100 (like availability).
---

feat: add PercentageAxisUpToHundred convenience axis

---

API.md
lib/common/alarm/AlarmFactory.ts
test/common/alarm/AlarmFactory.test.ts
test/common/alarm/__snapshots__/AlarmFactory.test.ts.snap

Closes #516
CloudWatch `CompositeAlarm` now supports specifying a suppressor alarm `actionsSuppressor` when initializing (see [CompositeAlarm API reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-compositealarm.html)). However, this additional parameter is not present within `AddCompositeAlarmProps`, and thus, it is not possible to create a `CompositeAlarm` using `AlarmFactory.addCompositeAlarm(...)` while simultaneously specifying a suppressor alarm. This pull request adds this functionality, while being backwards-compatible, since all new props are optional.
- `yarn build`
- Added suite of unit tests to test suppressor alarm prop behavior.
---
_By submitting this pull request, I confirm that my contribution is made under the terms of the …

feat(AlarmFactory): add suppressor alarm props to AddCompositeAlarmProps

---

API.md
lib/common/alarm/AlarmFactory.ts

No code logic changes.
Unfortunately missed changing `actionsSuppressorExtensionPeriod` prop description to use "duration" instead of "time in seconds". The "time in seconds" descriptor is used in [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-compositealarm.html), but since the prop type required by CDK `CompositeAlarm` is `Duration`, it's more accurate to use "duration" (and to be consistent with the [CDK Composite Alarm definition](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.CompositeAlarm.html)).
Note: This wording change was already done for `actionsSuppressorWaitPeriod`; only `actionsSuppressorExtensionPeriod` was missed.
- `yarn build` -- no code logic changes so no additional unit …

fix(AlarmFactory): Fix wording for actionsSuppressorExtensionPeriod prop to use 'duration' instead of 'time in seconds'

---

API.md
lib/monitoring/aws-ecs-patterns/BaseServiceMetricFactory.ts
lib/monitoring/aws-ecs-patterns/Ec2ServiceMonitoring.ts
lib/monitoring/aws-ecs-patterns/FargateServiceMonitoring.ts
test/monitoring/aws-ecs-patterns/Ec2ServiceMonitoring.test.ts
test/monitoring/aws-ecs-patterns/FargateServiceMonitoring.test.ts
test/monitoring/aws-ecs-patterns/__snapshots__/Ec2ServiceMonitoring.test.ts.snap
test/monitoring/aws-ecs-patterns/__snapshots__/FargateServiceMonitoring.test.ts.snap
test/monitoring/aws-loadbalancing/__snapshots__/ApplicationLoadBalancerMonitoring.test.ts.snap

feat(ecs): add ability to alarm on ephermal storage usage

---

.projen/deps.json
.projenrc.ts
README.md
lib/facade/MonitoringAspect.ts
package.json
test/facade/__snapshots__/MonitoringAspect.test.ts.snap

Fixes #212.
We don't _really_ use the L2 constructs directly, so we add our own rough type checking logic to replace the one usage we did have but retain the dev dependency for testing purposes.
For reference, [here's the current L2 `Cluster` implementation](https://github.com/aws/aws-cdk/blob/v2.146.0/packages/@aws-cdk/aws-redshift-alpha/lib/cluster.ts#L432).
---

feat: drop peer dependency on @aws-cdk/aws-redshift-alpha

---

API.md
lib/monitoring/aws-ecs-patterns/Ec2ServiceMonitoring.ts
lib/monitoring/aws-ecs-patterns/FargateServiceMonitoring.ts
lib/monitoring/aws-loadbalancing/ApplicationLoadBalancerMetricFactory.ts
lib/monitoring/aws-loadbalancing/LoadBalancerMetricFactory.ts
lib/monitoring/aws-loadbalancing/NetworkLoadBalancerMetricFactory.ts
lib/monitoring/aws-loadbalancing/NetworkLoadBalancerMonitoring.ts
test/monitoring/aws-ecs-patterns/__snapshots__/Ec2ServiceMonitoring.test.ts.snap
test/monitoring/aws-ecs-patterns/__snapshots__/FargateServiceMonitoring.test.ts.snap
test/monitoring/aws-loadbalancing/__snapshots__/ApplicationLoadBalancerMonitoring.test.ts.snap
test/monitoring/aws-loadbalancing/__snapshots__/NetworkLoadBalancerMonitoring.test.ts.snap

Fixes #532
This pull request adds fail-open monitoring to our Load Balancing monitors.
To give context about fail open ([ref](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html)):
> If a target group contains only unhealthy registered targets, the load balancer routes requests to all those targets, regardless of their health status. This means that if all targets fail health checks at the same time in all enabled Availability Zones, the load balancer fails open. The effect of the fail-open is to allow traffic to all targets in all enabled Availability Zones, regardless of their health status, based on the load balancing algorithm
Adding this metric will give better visibility into whether the Load Balancer's fail open routing was used …

feat(loadbalancing): add fail-open monitoring

---

lib/facade/MonitoringAspect.ts
lib/monitoring/aws-wafv2/WafV2MetricFactory.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-wafv2/WafV2Monitoring.test.ts

1. Throw an error at build time if we're missing the prop when it's needed.
2. Automatically get the region when needed when using `monitorScope`.
---

feat(wafv2): better handle contextually required region prop

---

README.md
lib/monitoring/aws-apigateway/ApiGatewayMetricFactory.ts
lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMetricFactory.ts
lib/monitoring/aws-appsync/AppSyncMetricFactory.ts
lib/monitoring/aws-billing/BillingMetricFactory.ts
lib/monitoring/aws-docdb/DocumentDbMetricFactory.ts
lib/monitoring/aws-ecs-patterns/BaseServiceMetricFactory.ts
lib/monitoring/aws-lambda/LambdaFunctionMetricFactory.ts
lib/monitoring/aws-loadbalancing/ApplicationLoadBalancerMetricFactory.ts
lib/monitoring/aws-loadbalancing/NetworkLoadBalancerMetricFactory.ts
lib/monitoring/aws-rds/RdsClusterMetricFactory.ts
lib/monitoring/aws-rds/RdsInstanceMetricFactory.ts
lib/monitoring/aws-step-functions/StepFunctionLambdaIntegrationMetricFactory.ts
lib/monitoring/aws-step-functions/StepFunctionMetricFactory.ts
lib/monitoring/aws-step-functions/StepFunctionServiceIntegrationMetricFactory.ts
lib/monitoring/aws-synthetics/SyntheticsCanaryMetricFactory.ts

Pulling out irrelevant code cleanup from #544.
Also clarifying in docs that cross-region alarms are not supported by CloudWatch.
---

chore: minor cleanup

---

lib/common/monitoring/alarms/AgeAlarmFactory.ts

Our team has tiered alarms on the max iterator age of events going to a Lambda function so that we get higher severity tickets for higher iterator ages which indicates worse backups in processing.
However, these are not currently deduping into the same ticket which I root caused to the `alarmDedupeStringSuffix` being missing on the `addIteratorMaxAgeAlarm` which the Lambda monitoring uses.
This PR fixes this.
---

fix(lambda): fix iterator age dedupe

---

API.md
lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts
test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts
test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap

We've received feedback that the default IteratorAge widget is largely useless for any Lambda function that isn't actually a stream handler. Function doesn't provide a way to really tell if that's the case, so we ended up with an explicit prop.
We default to true for backwards compat.
---

feat(lambda): add isIterator prop

---

API.md
lib/common/monitoring/alarms/AgeAlarmFactory.ts
lib/monitoring/aws-lambda/LambdaFunctionMetricFactory.ts
lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/facade/__snapshots__/MonitoringFacade.test.ts.snap
test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts
test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap

Lambda has added support for connecting to Kafka streams via Event Source Mappings (see: https://docs.aws.amazon.com/lambda/latest/dg/with-msk.html). This comes with the addition of a new CW metric under the AWS/Lambda namespace, `OffsetLag` (see: https://aws.amazon.com/blogs/compute/offset-lag-metric-for-amazon-msk-as-an-event-source-for-lambda/). This metric is different than the existing IteratorAge metric used for Kinesis streams. OffsetLag represents the difference between the last record written to a Kafka topic and the last record that the function's consumer group has processed (note the metric is in # of records, it's not a time metric). See here: https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics.html.
Defaulted the monitor to `false` since it's a new prop and is …

feat(lambda): add isOffsetLag prop for alarms/dashboards for OffsetLag metric

---

API.md
lib/common/alarm/CustomAlarmThreshold.ts

This provides support for `minSampleCountToEvaluateDatapoint` when using eg. `ErrorAlarmFactory`. Without this change and with a `MathExpression` containing multiple metrics, one would get the following error:
> "sampleCountMetricId must be specified when using minSampleCountToEvaluateDatapoint with a multiple-metric MathExpression"
However `sampleCountMetricId` is currently not available in `CustomAlarmThreshold`.
See https://github.com/cdklabs/cdk-monitoring-constructs/pull/466 for original change.
---

fix: Add sampleCountMetricId to CustomAlarmThreshold

---

API.md
README.md
lib/common/metric/MetricFactory.ts

Fixes #583
Also includes minor README fixes noted in that issue.
---

fix(MetricFactory): more specific return type for createMetricSearch

---

lib/common/monitoring/alarms/LatencyAlarmFactory.ts
test/common/alarm/LatencyAlarmFactory.test.ts

Fixes #586.
Adds the `integral: false` option to [`Duration.toMillisecond()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Duration.html#towbrmillisecondsopts) calls to allow the original non-integral/sub-millisecond threshold values to be provided to CloudWatch. These four lines are the only uses of `toMilliseconds` in the package.
I also created a new test for the `LatencyAlarmFactory` class to test these specific cases. To verify that they were working, I ran the tests without the fix in place and got the expected error messages: [gist](https://gist.github.com/sajidanw/37fd1ddd63ff763a911bb3a1cf58b2b8).
---

fix: Allow non-integral latency thresholds and durations

---

lib/dashboard/MonitoringNamingStrategy.ts
test/dashboard/MonitoringNamingStrategy.test.ts

FIFO queues require a suffix of ".fifo" and thus do not work without alarm name overrides. This is tedious.
---

feat: allow periods (".") in alarm names

---

.github/workflows/release.yml
.projenrc.ts

> The following actions use a deprecated Node.js version and will be forced to run on node20: slackapi/slack-github-action@v1.24.0. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
eg: https://github.com/cdklabs/cdk-monitoring-constructs/actions/runs/11822135099/job/32938877139
---

chore(workflow): Update slack notification action

---

API.md
lib/monitoring/aws-cloudfront/CloudFrontDistributionMonitoring.ts
lib/monitoring/aws-wafv2/WafV2Monitoring.ts
test/facade/MonitoringAspect.test.ts
test/facade/__snapshots__/MonitoringAspect.test.ts.snap

Fixes #607
Also replaces some things marked as deprecated in the unit tests just to make it less noisy.
---

fix(MonitoringAspect): allow specifying CloudFrontDistribution and WafV2 alarms

---

API.md
lib/common/alarm/AlarmFactory.ts
lib/common/alarm/CustomAlarmThreshold.ts
test/monitoring/aws-ecs-patterns/FargateServiceMonitoring.test.ts
test/monitoring/aws-ecs-patterns/__snapshots__/FargateServiceMonitoring.test.ts.snap

Addresses a gap where the deduplication string wasn’t easily customizable via typical facade usage. It can be customized using dedupeStringOverride, but this overrides the entire deduplication string. Since alarm name prefixes (globalPrefix, localPrefix in AlarmNamingStrategy) are usually specified, alarmDedupeStringSuffix is more convenient in use.
I've observed many cases where dedupeStringOverride is used, with the string being
manually constructed by concatenating prefixes passed as parameters to the facade.
---

feat: Allow specifying alarmDedupeStringSuffix in CustomAlarmThreshold

---

API.md
lib/monitoring/aws-apigateway/ApiGatewayMetricFactory.ts
lib/monitoring/aws-apigateway/ApiGatewayMonitoring.ts
lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMetricFactory.ts
lib/monitoring/aws-apigatewayv2/ApiGatewayV2HttpApiMonitoring.ts
lib/monitoring/aws-appsync/AppSyncMetricFactory.ts
lib/monitoring/aws-appsync/AppSyncMonitoring.ts
lib/monitoring/aws-cloudfront/CloudFrontDistributionMetricFactory.ts
lib/monitoring/aws-cloudfront/CloudFrontDistributionMonitoring.ts
lib/monitoring/aws-lambda/LambdaFunctionMetricFactory.ts
lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts
lib/monitoring/aws-opensearch/OpenSearchClusterMetricFactory.ts
lib/monitoring/aws-opensearch/OpenSearchClusterMonitoring.ts

So we can fully remove these later.
---

chore: replace usages of deprecated TPS metric methods

---

API.md
lib/common/alarm/AlarmFactory.ts
lib/common/alarm/IAlarmNamingStrategy.ts
test/common/alarm/AlarmFactory.test.ts

This can be useful if you want to name the alarm based on properties of the action being applied.
---

feat(AlarmFactory): allow accessing action strategy as part of alarm naming strategy

---

API.md
lib/monitoring/aws-kinesis/KinesisFirehoseMonitoring.ts
test/monitoring/aws-kinesis/KinesisFirehoseMonitoring.test.ts
test/monitoring/aws-kinesis/__snapshots__/KinesisFirehoseMonitoring.test.ts.snap

The conversions widget is useless for any Firehose which doesn't have data format conversions enabled.
Default is true for backwards compatability.
Implementation is based on the similar `isIterator` parameter for Lambda Functions. 
Note that the AWS docs are not consistent about what they call this feature, [sometimes calling it data format conversion, sometimes calling it record format conversion](https://docs.aws.amazon.com/firehose/latest/dev/enable-record-format-conversion.html). CDK calls it [data format conversion](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kinesisfirehose.CfnDeliveryStream.DataFormatConversionConfigurationProperty.html), hence my choice to use that terminology for the parameter too.
The library doesn't currently support enabling alarms on any of …

feat(KinesisFirehoseMonitoring): add isDataFormatConversionEnabled prop

---

lib/monitoring/aws-dynamo/DynamoTableGlobalSecondaryIndexMonitoring.ts
test/monitoring/aws-dynamo/DynamoTableGlobalSecondaryIndexMonitoring.test.ts
test/monitoring/aws-dynamo/__snapshots__/DynamoTableGlobalSecondaryIndexMonitoring.test.ts.snap

Fixes #628
This change passes the BaseMonitoringProps passed into DynamoTableGlobalSecondaryIndexMonitoring along to the super class constructor, which exposes `localAlarmNamePrefixOverride` to be consumed by Monitoring.createAlarmFactory. Additionally, this changes the construction of the alarm factory to use `createAlarmFactory` from the parent class (thus using `localAlarmNamePrefixOverride`, rather than that from the parent scope (MonitoringFacade, which doesn't have  `localAlarmNamePrefixOverride` available).
By doing so, we achieve the more expected behavior of having `localAlarmNamePrefixOverride` influence the local portion of the alarm name. By default, that portion is just the GSI name itself, and there are cases where this can cause collisions (e.g. two GSIs with the same name …

fix(dynamo): adjusts DynamoTableGlobalSecondaryIndexMonitoring to respect localAlarmNamePrefixOverride

---

lib/dashboard/widget/BitmapWidget.ts
lib/monitoring/aws-secretsmanager/SecretsManagerMetricsPublisher.ts
test/common/alarm/action/LambdaAlarmActionStrategy.test.ts
test/dashboard/widget/CustomWidget.test.ts
test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts
test/monitoring/aws-step-functions/StepFunctionLambdaIntegrationMonitoring.test.ts

Node.js 18 will be blocked later this year.
See https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
---

fix: use latest Node.js runtime for utility Lambda functions

---

API.md
README.md
lib/common/alarm/AlarmFactory.ts
lib/common/alarm/ScaleAlarms.ts
lib/common/alarm/index.ts
lib/facade/MonitoringFacade.ts
test/common/alarm/ScaleAlarms.test.ts
test/common/alarm/__snapshots__/ScaleAlarms.test.ts.snap
test/facade/MonitoringFacade.test.ts
test/facade/__snapshots__/MonitoringFacade.test.ts.snap

Closes #631
---
The changes in this pull request implement [a feature to clone conservative ticketing alarms to be more aggressive for rollback alarms](https://github.com/cdklabs/cdk-monitoring-constructs/issues/631). `MonitoringFacade` introduces the capability to specify that all monitors belonging to a given disambiguator (e.g. "Critical") should be cloned to new monitors with a new different disambiguator (e.g. "Rollback") and mutated to a smaller number of datapoints to alarm.
There are two parts to this feature.
The `MonitoringFacade` class now has a `cloneAlarms()` method. When given a list of `AlarmWithAnnotation` objects and a TypeScript function, the `cloneAlarms()` method applies the function on each alarm in the list. The clone function itself takes an `AlarmWithAnnotation` …

feat: add ability to clone monitors

---

lib/common/metric/MetricFactory.ts
test/common/metric/MetricFactory.test.ts
test/common/metric/__snapshots__/MetricFactory.test.ts.snap

This change splits the namespaces to wrap them individually.
Fixes #623
---

fix(MetricFactory): Metric Search with multiple namespaces are wrongly wrapped

---

lib/dashboard/widget/BitmapWidget.ts
lib/monitoring/aws-secretsmanager/SecretsManagerMetricsPublisher.ts
test/common/alarm/action/LambdaAlarmActionStrategy.test.ts
test/common/alarm/action/__snapshots__/LambdaAlarmActionStrategy.test.ts.snap
test/dashboard/widget/CustomWidget.test.ts
test/dashboard/widget/__snapshots__/BitmapWidget.test.ts.snap
test/facade/__snapshots__/MonitoringAspect.test.ts.snap
test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts
test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap
test/monitoring/aws-secretsmanager/__snapshots__/SecretsManagerSecretMonitoring.test.ts.snap
test/monitoring/aws-step-functions/StepFunctionLambdaIntegrationMonitoring.test.ts
test/monitoring/aws-step-functions/__snapshots__/StepFunctionLambdaIntegrationMonitoring.test.ts.snap

`NODEJS_LATEST` still points to Node.js 18, which is already EOL.
Related upstream issue: https://github.com/aws/aws-cdk/issues/28125
---

feat: use dynamically determined latest Node.js runtime for Lambda handlers instead

---

API.md
lib/dashboard/DefaultDashboardFactory.ts
lib/dashboard/DynamicDashboardFactory.ts
test/dashboard/DefaultDashboardFactory.test.ts
test/dashboard/DynamicDashboardFactory.test.ts

Fixes https://github.com/cdklabs/cdk-monitoring-constructs/issues/391
Not sure if this change is really needed — I’ve been creating dashboards with variables by just grabbing the underlying dashboards and attaching variables that way. That said, it’s a nice cleanup and does make the code a bit cleaner. Totally fine to close the PR if you don’t think it’s worth it.
---

feat(dashboard): add support for dashboard variables

---

API.md
lib/common/monitoring/alarms/LatencyAlarmFactory.ts
lib/monitoring/aws-lambda/LambdaFunctionEnhancedMetricFactory.ts
lib/monitoring/aws-lambda/LambdaFunctionMonitoring.ts
test/monitoring/aws-lambda/LambdaFunctionMonitoring.test.ts
test/monitoring/aws-lambda/__snapshots__/LambdaFunctionMonitoring.test.ts.snap

Fixes https://github.com/cdklabs/cdk-monitoring-constructs/issues/462
Add `init_duration` to `LambdaFunctionMonitoring`. Monitoring INIT has become increasingly important due to:
1. Lambda now bills for the INIT phase. [Blog](https://aws.amazon.com/blogs/compute/aws-lambda-standardizes-billing-for-init-phase/).
2. With the growing adoption of Provisioned Concurrency and SnapStart, people want visibility into INIT durations.
While making changes for the PR, I noticed an issue with how the function cost is calculated (https://github.com/cdklabs/cdk-monitoring-constructs/issues/645). I’ll fix that next and also include INIT as part of the cost calculation.
---

feat(lambda): Add widget and alarms on init duration

---

API.md
lib/monitoring/aws-cloudwatch/LogMonitoring.ts
test/monitoring/aws-cloudwatch/LogMonitoring.test.ts
test/monitoring/aws-cloudwatch/__snapshots__/LogMonitoring.test.ts.snap

Introduces `filterExpressions: string[]` as an additional option to filter logs
Fixes #643 
---

feat(LogMonitoring): Added filterExpressions to enable advanced JSON log queries
